version: '3'

services:

  super-shiharai-kun-api:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8080:8080
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8080
    volumes:
      - $PWD/package*:/docker/super-shiharai-kun/*
      - $PWD/src/*:/docker/super-shiharai-kun/src/*
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:5.7
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=local_super_shiharai_kun
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - $PWD/.mysql/data/main:/var/lib/mysql