version: '3'

services:

  super-shiharai-kun-api:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8080:8080
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8080
    volumes:
      - $PWD/package*:/docker/super-shiharai-kun/*
      - $PWD/src/*:/docker/super-shiharai-kun/src/*
